name: seva_sanskriti
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  lottie: ^3.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  dotted_border: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.2
  permission_handler: ^10.0.0
  fast_contacts: ^3.0.3
  flutter_native_splash: ^2.3.10
  contacts_service: ^0.6.3
  firebase_storage: ^11.6.10
  intl: ^0.19.0
  maps_launcher: ^2.2.1
  mailer: ^6.1.0
  upi_india: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  background_image: assets/splash_bg.png
  background_image_dark: assets/splash_bg.png
  android: true
  ios: true
  android_12:
    background_image: assets/splash_bg.png
    background_image_dark: assets/splash_bg.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/